name: Merge into main

on:
  push:
    branches:
      - main

permissions:
  # write to contents and pull-requests required for release-please
  contents: write
  pull-requests: write

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  release-please:
    runs-on: ubuntu-latest
    outputs:
      releases_created: ${{ steps.release-please.outputs.releases_created }}
    steps:
      - uses: google-github-actions/release-please-action@v3
        id: release-please
        with:
          release-type: node
          package-name: eventbridge-toolbox
  publish-package:
    runs-on: ubuntu-latest
    needs: release-please
    if: ${{ needs.release-please.outputs.releases_created  }}
    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2
        with:
          version: 7.27.0
      - uses: actions/setup-node@v3
        with:
          cache: "pnpm"
      - name: ğŸ’« Install dependencies
        run: pnpm install --frozen-lockfile
      - name: ğŸ¡ Build
        run: pnpm run build
      - name: ğŸš€ Publish eventbridge-toolbox
        run: pnpm publish --access=public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
